name: Deploy docs

# O workflow será executado toda vez que houver um push na branch main
on:
  push:
    branches:
      - main

# Trabalhos que serão executados
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Instalação das dependências de produção no ambiente de CI (isto significa que não modifica o package-lock.json)
      - run: npm ci

      # Executa o script "build": "turbo run build", portanto, roda a build de todos os pacotes
      - run: npm run build

      - name: Deploy storybook
        working-directory: ./packages/docs
        run: touch storybook-static/.nojekyll && npm run deploy-storybook -- --ci --existing-output-dir=storybook-static
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}

# Observação: jekyll (usado por padrão pelo gh-pages) ignora arquivos começados por underline. Isto resulta no erro Failed to fetch dynamically imported module
# quando tentamos acessar a página do Design System no GitHub Pages. Para resolver isso é só adicionar o arquivo .nojekyll na branch gh-pages ou adicionar o 
# comando touch storybook-static/.nojekyll no run do Deploy storybook 

# Links
# https://github.com/storybook-eol/storybook-deployer
# https://github.com/storybookjs/storybook/issues/20564